//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolSizeCalc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VolSizeCalc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD DRIVE SIZE.
        /// </summary>
        internal static string AddDriveSize {
            get {
                return ResourceManager.GetString("AddDriveSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant add more than 60 different sizes of drives..
        /// </summary>
        internal static string CantAddMore {
            get {
                return ResourceManager.GetString("CantAddMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to default the drive size entries to default?.
        /// </summary>
        internal static string DefautMessage {
            get {
                return ResourceManager.GetString("DefautMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE DRIVE SIZE.
        /// </summary>
        internal static string DeleteDriveSize {
            get {
                return ResourceManager.GetString("DeleteDriveSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: The numbers here are based on a calculation and may vary in the actual system. Also note this program is time independent meaning it does not care about the chronological order that you add or remove drives. In real-life each system preforms under its very own characteristics when drives are added and does depend on time(in a way), for example: if your first drive was a 2TB drive, I would not be able to add smaller drives there after to expand. So hence, each calculation is as if you have factory defa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ico1 {
            get {
                object obj = ResourceManager.GetObject("ico1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is an invalid drive size. Just write the number in GB without the unit. So if it was 750 GB drive. I would just write 750..
        /// </summary>
        internal static string InvalidDriveSize {
            get {
                return ResourceManager.GetString("InvalidDriveSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got to have at least 1 drive size on the screen..
        /// </summary>
        internal static string NeedAtLeast1Drive {
            get {
                return ResourceManager.GetString("NeedAtLeast1Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What size of drive would you like to add? [Gigabytes in base 10, drive manufacturer units].
        /// </summary>
        internal static string WhatToAdd {
            get {
                return ResourceManager.GetString("WhatToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What drive would you like to delete? [Just write the GB size of the drive, so if had a 4000 GB drive I would just type 4000].
        /// </summary>
        internal static string WhatToDelete {
            get {
                return ResourceManager.GetString("WhatToDelete", resourceCulture);
            }
        }
    }
}
